-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


ALTER TABLE IF EXISTS public.dept_employees DROP CONSTRAINT IF EXISTS dept_num;

ALTER TABLE IF EXISTS public.dept_employees DROP CONSTRAINT IF EXISTS None;

ALTER TABLE IF EXISTS public.dept_managers DROP CONSTRAINT IF EXISTS dept_num;

ALTER TABLE IF EXISTS public.dept_managers DROP CONSTRAINT IF EXISTS None;

ALTER TABLE IF EXISTS public.employees DROP CONSTRAINT IF EXISTS None;

ALTER TABLE IF EXISTS public.salaries DROP CONSTRAINT IF EXISTS None;



DROP TABLE IF EXISTS public.departments;

CREATE TABLE IF NOT EXISTS public.departments
(
    dept_num character varying(5)[] NOT NULL,
    dept_name character varying(50)[] NOT NULL,
    CONSTRAINT dept_num PRIMARY KEY (dept_num)
);

DROP TABLE IF EXISTS public.dept_employees;

CREATE TABLE IF NOT EXISTS public.dept_employees
(
    id bigint NOT NULL,
    employee_num character varying(10)[] NOT NULL,
    dept_num character varying(5)[] NOT NULL,
    CONSTRAINT id PRIMARY KEY (id)
);

DROP TABLE IF EXISTS public.dept_managers;

CREATE TABLE IF NOT EXISTS public.dept_managers
(
    id bigint NOT NULL,
    dept_num character varying(5)[] NOT NULL,
    employee_num character varying(10)[] NOT NULL,
    CONSTRAINT id PRIMARY KEY (id)
);

DROP TABLE IF EXISTS public.employees;

CREATE TABLE IF NOT EXISTS public.employees
(
    employee_num character varying[] NOT NULL,
    employee_title_id character varying[] NOT NULL,
    birth_date date NOT NULL,
    first_name character varying[] NOT NULL,
    last_name character varying[] NOT NULL,
    sex "char" NOT NULL,
    hire_date date NOT NULL,
    CONSTRAINT employee_num PRIMARY KEY (employee_num)
);

DROP TABLE IF EXISTS public.salaries;

CREATE TABLE IF NOT EXISTS public.salaries
(
    employee_num character varying[] NOT NULL,
    salary bigint NOT NULL,
    CONSTRAINT employee_num PRIMARY KEY (employee_num)
);

DROP TABLE IF EXISTS public.titles;

CREATE TABLE IF NOT EXISTS public.titles
(
    title_id character varying(10)[] NOT NULL,
    title character varying(30)[] NOT NULL,
    CONSTRAINT title_id PRIMARY KEY (title_id)
);

ALTER TABLE IF EXISTS public.dept_employees
    ADD CONSTRAINT dept_num FOREIGN KEY (dept_num)
    REFERENCES public.departments (dept_num) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.dept_employees
    ADD FOREIGN KEY (employee_num)
    REFERENCES public.employees (employee_num) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.dept_managers
    ADD CONSTRAINT dept_num FOREIGN KEY (dept_num)
    REFERENCES public.departments (dept_num) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.dept_managers
    ADD FOREIGN KEY (employee_num)
    REFERENCES public.employees (employee_num) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.employees
    ADD FOREIGN KEY (employee_title_id)
    REFERENCES public.titles (title_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.salaries
    ADD FOREIGN KEY (employee_num)
    REFERENCES public.employees (employee_num) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;